// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCJ9d4QzVdvn92eS2WQrZtDL3q1MfKnyg',
    appId: '1:908354790229:web:a12d15a3a60efb99ad85dc',
    messagingSenderId: '908354790229',
    projectId: 'trace-34749',
    authDomain: 'trace-34749.firebaseapp.com',
    storageBucket: 'trace-34749.appspot.com',
    measurementId: 'G-TR7P2ST3CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_mkJBdpaVkAB8TzsbMIbAVDEDbNNFPM',
    appId: '1:908354790229:android:c885716dc63e6827ad85dc',
    messagingSenderId: '908354790229',
    projectId: 'trace-34749',
    storageBucket: 'trace-34749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ6OWxETQWcanqL6iTRP_CnBMpE0uqFvU',
    appId: '1:908354790229:ios:028f6fb35fd47d6fad85dc',
    messagingSenderId: '908354790229',
    projectId: 'trace-34749',
    storageBucket: 'trace-34749.appspot.com',
    androidClientId: '908354790229-4pfj0hgmv4gjegs9qq3t9feohp9baahn.apps.googleusercontent.com',
    iosClientId: '908354790229-5j91atkrp9ms2rbn5qbcgdae7d9a5da2.apps.googleusercontent.com',
    iosBundleId: 'com.trace.appsdabanda',
  );
}
